# Generated by Django 5.1.2 on 2024-10-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0006_bankaccount_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('suspended', 'Suspended'), ('unsuspended', 'Unsuspended')], default='active', max_length=15),
        ),
    ]
